server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/author_book_mudular
    username: root
    password: root

  jpa:
    show-sql: true

  liquibase:
    change-log: classpath:/liquibase/changelog.xml

jwt:
  secret: YXNkZmYkIyNzZFNEU0RBQVNERksjQEBkc2ZqZGZrZHNqQEAjZHNmZ2ZnZmdeXiYmWipeJSQkI2RzZHMkIyVzZDQ1MDk5KUkjJCg5V0ZTSUo=
  expiration: 600000

  springdoc:
    packages-to-scan: itspace.authorbookrest.endpoint
countries:
  api:
   key: 273|HlHmeugKDPgtMprcd5WVP5BNAOCQFHKLMQNhYplP

upload:
  image:
    path: C:\\Users\\Admin\\data\\lesons\\Java2022-23\\author-book-modular\\images\\

site:
  url: http://localhost:8081